### ISSUE TITLE
顯示時，將 _slack_bot1 的 nickname 換成 slack 發言者的 nickname

### ISSUE THREAD

**Issue by audreyt** [g0v/Logbot#22]
例如 http://logbot.g0v.tw/channel/g0v.tw/2014-12-24/60 和 http://logbot.g0v.tw/channel/g0v.tw/2014-12-24#60 ，發言者的名稱在顯示層應為 t0mst0ne

**Comment by caasi** [comment]
可以假裝成不存在的人： http://logbot.g0v.tw/channel/g0v.tw/2015-05-21/32

還想不到好的解法。

**Comment by audreyt** [comment]
是還好啦，IRC 原本就可以自己亂 /nick 成別人。
不涉及 privmsg/nickserv 的話，不用特別去解 XD

**Comment by caasi** [comment]
瞭解 XD
