### ISSUE TITLE
支援 Slack 頻道來的 Emoji 

### ISSUE THREAD

**Issue by audreyt** [g0v/Logbot#27]
e.g. https://github.com/Ranks/emojione

<img width="412" alt="2015-07-16 3 41 21" src="https://cloud.githubusercontent.com/assets/20723/8717790/20ffe728-2bd1-11e5-9187-9317ea5cf6fa.png">

**Comment by caasi** [comment]
需要更多對應表 XD
https://github.com/g0v/Logbot/blob/b55017837250f07307a8a22822d61e5d2a0934af/public/emoji.js#L4

**Comment by caasi** [comment]
詳見： 0fdf1a1
