### ISSUE TITLE
& in URLs mis-escaped to &amp;

### ISSUE THREAD

**Issue by audreyt** [g0v/Logbot#29]
e.g. https://logbot.g0v.tw/channel/g0v.tw/2016-12-26/1 results in invalid link

reported by michael_li

**Comment by godfat** [comment]
Looks like it's double escaped.

**Comment by godfat** [comment]
Umm... I don't feel we're really double escaping it. It was from `slackbot4`, which might have escaped it in the first place?

If this is the case, I am not sure if we could fix this.
